name: e2e test
on: [push]
jobs:
  e2e-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: 14.x
          cache: "npm"
      - run: npx playwright install-deps
      - run: npm ci
      - run: npm test
